name: zeroleft
description: "식료품 유통기한 관리 앱 - ZeroLeft"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  
  # Database & Storage
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  permission_handler: ^11.0.1
  
  # Date & Time
  intl: 0.20.2
  table_calendar: ^3.0.9
  
  # UI/UX
  flutter_slidable: ^3.0.1
  flutter_animate: ^4.3.0
  flutter_staggered_animations: ^1.1.1
  
  # Utils
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.3.0+4

flutter:
  uses-material-design: true